CREATE TABLE public.users (
    tg_id BIGINT PRIMARY KEY,
    first_name TEXT NOT NULL,
    company TEXT
);


CREATE TABLE public.bookings (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_datetime TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL
);
