version: '3.7'

services:
  sapaplus:
    container_name: "${CONTAINER_NAME}"
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./app/.env
    working_dir: /app
    command: ["python", "bot/bot.py"]
    networks:
      - postgres
    depends_on:
      - postgresql         # ✅ теперь в нужном месте
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  postgresql:               # ✅ Добавь сюда, если его нет
    image: postgres:17-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
